namespace ProjectMER.Commands.Utility.MapConverter.OldMapEditorRebornCodes.OldEnums
{
    public enum OldRoleTypeId : sbyte
    {
        None = -1,
        Scp173,
        ClassD,
        Spectator,
        Scp106,
        NtfSpecialist,
        Scp049,
        Scientist,
        Scp079,
        ChaosConscript,
        Scp096,
        Scp0492,
        NtfSergeant,
        NtfCaptain,
        NtfPrivate,
        Tutorial,
        FacilityGuard,
        Scp939,
        CustomRole,
        ChaosRifleman,
        ChaosMarauder,
        ChaosRepressor,
        Overwatch,
        Filmmaker,
        Scp3114,
        Destroyed,
        Flamingo,
        AlphaFlamingo,
        ZombieFlamingo
    }
    public enum OldDoorType
    {
        UnknownDoor,
        Scp914Door,
        GR18Inner,
        Scp049Gate,
        Scp049Armory,
        Scp079First,
        Scp079Second,
        Scp096,
        Scp079Armory,
        Scp106Primary,
        Scp106Secondary,
        Scp173Gate,
        Scp173Connector,
        Scp173Armory,
        Scp173Bottom,
        GR18Gate,
        Scp914Gate,
        Scp939Cryo,
        CheckpointLczA,
        CheckpointLczB,
        EntranceDoor,
        EscapePrimary,
        EscapeSecondary,
        GateA,
        GateB,
        HczArmory,
        HeavyContainmentDoor,
        HeavyBulkDoor,
        HIDChamber,
        HIDUpper,
        HIDLower,
        Intercom,
        LczArmory,
        LczCafe,
        LczWc,
        LightContainmentDoor,
        NukeArmory,
        NukeSurface,
        PrisonDoor,
        SurfaceGate,
        Scp330,
        Scp330Chamber,
        CheckpointGateA,
        CheckpointGateB,
        SurfaceDoor,
        CheckpointEzHczA,
        CheckpointEzHczB,
        UnknownGate,
        UnknownElevator,
        ElevatorGateA,
        ElevatorGateB,
        ElevatorNuke,
        ElevatorScp049,
        ElevatorLczA,
        ElevatorLczB,
        CheckpointArmoryA,
        CheckpointArmoryB,
        Airlock,
        Scp173NewGate,
        EscapeFinal
    }
    [Flags]
    public enum OldKeycardPermissions : ushort
    {
        None = 0,
        Checkpoints = 1,
        ExitGates = 2,
        Intercom = 4,
        AlphaWarhead = 8,
        ContainmentLevelOne = 0x10,
        ContainmentLevelTwo = 0x20,
        ContainmentLevelThree = 0x40,
        ArmoryLevelOne = 0x80,
        ArmoryLevelTwo = 0x100,
        ArmoryLevelThree = 0x200,
        ScpOverride = 0x400
    }
    [Flags]
    public enum OldDoorDamageType : byte
    {
        None = 1,
        ServerCommand = 2,
        Grenade = 4,
        Weapon = 8,
        Scp096 = 0x10,
        ParticleDisruptor = 0x20
    }
    [Flags]
    public enum OldLockOnEvent
    {
        None = 0,
        LightDecontaminated = 1,
        WarheadDetonated = 2,
    }
    public enum OldItemType
    {
        None = -1,
        KeycardJanitor,
        KeycardScientist,
        KeycardResearchCoordinator,
        KeycardZoneManager,
        KeycardGuard,
        KeycardMTFPrivate,
        KeycardContainmentEngineer,
        KeycardMTFOperative,
        KeycardMTFCaptain,
        KeycardFacilityManager,
        KeycardChaosInsurgency,
        KeycardO5,
        Radio,
        GunCOM15,
        Medkit,
        Flashlight,
        MicroHID,
        SCP500,
        SCP207,
        Ammo12gauge,
        GunE11SR,
        GunCrossvec,
        Ammo556x45,
        GunFSP9,
        GunLogicer,
        GrenadeHE,
        GrenadeFlash,
        Ammo44cal,
        Ammo762x39,
        Ammo9x19,
        GunCOM18,
        SCP018,
        SCP268,
        Adrenaline,
        Painkillers,
        Coin,
        ArmorLight,
        ArmorCombat,
        ArmorHeavy,
        GunRevolver,
        GunAK,
        GunShotgun,
        SCP330,
        SCP2176,
        SCP244a,
        SCP244b,
        SCP1853,
        ParticleDisruptor,
        GunCom45,
        SCP1576,
        Jailbird,
        AntiSCP207,
        GunFRMG0,
        GunA7,
        Lantern,
        SCP1344,
        Snowball,
        Coal,
        SpecialCoal,
        SCP1507Tape
    }
    public enum OldRoomType
    {
        Unknown,
        LczArmory,
        LczCurve,
        LczStraight,
        Lcz914,
        LczCrossing,
        LczTCross,
        LczCafe,
        LczPlants,
        LczToilets,
        LczAirlock,
        Lcz173,
        LczClassDSpawn,
        LczCheckpointB,
        LczGlassBox,
        LczCheckpointA,
        Hcz079,
        HczEzCheckpointA,
        HczEzCheckpointB,
        HczArmory,
        Hcz939,
        HczHid,
        Hcz049,
        HczCrossing,
        Hcz106,
        HczNuke,
        HczTesla,
        HczCurve,
        Hcz096,
        EzVent,
        EzIntercom,
        EzGateA,
        EzDownstairsPcs,
        EzCurve,
        EzPcs,
        EzCrossing,
        EzCollapsedTunnel,
        EzConference,
        EzChef,
        EzStraight,
        EzStraightColumn,
        EzCafeteria,
        EzUpstairsPcs,
        EzGateB,
        EzShelter,
        Pocket,
        Surface,
        HczStraight,
        EzTCross,
        Lcz330,
        EzCheckpointHallwayA,
        EzCheckpointHallwayB,
        HczTestRoom,
        HczElevatorA,
        HczElevatorB,
        HczCrossRoomWater,
        HczCornerDeep,
        HczIntersectionJunk,
        HczIntersection,
        HczStraightC,
        HczStraightPipeRoom,
        HczStraightVariant,
        EzSmallrooms
    }
    public enum OldSpawnableTeam
    {
        None = -1,
        Scp049,
        Scp0492,
        Scp079,
        Scp096,
        Scp106,
        Scp173,
        Scp939,
        ClassD,
        Scientist,
        FacilityGuard,
        MTF,
        Chaos,
        Tutorial,
    }
    public enum OldShootingTargetType
    {
        Unknown,
        Sport,
        ClassD,
        Binary
    }
    public enum OldPrimitiveType
    {
        Sphere,
        Capsule,
        Cylinder,
        Cube,
        Plane,
        Quad
    }
    [Flags]
    public enum OldPrimitiveFlags : byte
    {
        None = 0,
        Collidable = 1,
        Visible = 2
    }
    [Flags]
    public enum OldTeleportFlags
    {
        None = 0,
        Player = 1,
        Pickup = 2,
        ActiveGrenade = 4,
    }
    public enum OldLockerType
    {
        Pedestal = 0,
        LargeGun = 1,
        RifleRack = 2,
        Misc = 3,
        Medkit = 4,
        Adrenaline = 5,
    }
    public enum OldAttachmentName
    {
        None,
        IronSights,
        DotSight,
        HoloSight,
        NightVisionSight,
        AmmoSight,
        ScopeSight,
        StandardStock,
        ExtendedStock,
        RetractedStock,
        LightweightStock,
        HeavyStock,
        RecoilReducingStock,
        Foregrip,
        Laser,
        Flashlight,
        AmmoCounter,
        StandardBarrel,
        ExtendedBarrel,
        SoundSuppressor,
        FlashHider,
        MuzzleBrake,
        MuzzleBooster,
        StandardMagFMJ,
        StandardMagAP,
        StandardMagJHP,
        ExtendedMagFMJ,
        ExtendedMagAP,
        ExtendedMagJHP,
        DrumMagFMJ,
        DrumMagAP,
        DrumMagJHP,
        LowcapMagFMJ,
        LowcapMagAP,
        LowcapMagJHP,
        CylinderMag5,
        CylinderMag6,
        CylinderMag7,
        CarbineBody,
        RifleBody,
        ShortBarrel,
        ShotgunChoke,
        ShotgunExtendedBarrel,
        NoRifleStock,
        ShotgunSingleShot,
        ShotgunDoubleShot
    }
    public enum OldCullingType
    {
        None = 0,
        Zone = 1,
        Distance = 2,
    }
}
